name = "alicesaidhi/jabby"
version = "0.1.0"
authors = ["alicesaidhi"]
repository = "https://github.com/alicesaidhi/jabby"
license = "MIT"
private = true

workspace_members = ["modules/*"]

[target]
environment = "roblox"

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }
