name = "alicesaidhi/jabby_ecs_registry_ecr"
version = "0.1.0"
includes = ["src/*", "pesde.toml"]
license = "MIT"

[target]
environment = "roblox"
lib = "src/lib.luau"
build_files = ["src"]

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[indices]
default = "https://github.com/daimond113/pesde-index"

[dependencies]
jabby_types = { workspace = "alicesaidhi/jabby_types" }
jabby_core = { workspace = "alicesaidhi/jabby_core" }
jabby_ui = { workspace = "alicesaidhi/jabby_ui" }
jabby_home = { workspace = "alicesaidhi/jabby_home" }
jabby_ecs_registry = { workspace = "alicesaidhi/jabby_ecs_registry" }
jabby_query_parser = { workspace = "alicesaidhi/jabby_query_parser" }
jabby_util = { workspace = "alicesaidhi/jabby_util" }
lua_preview_notation = { workspace = "alicesaidhi/lua_preview_notation" }
lua_object_notation = { workspace = "alicesaidhi/lua_object_notation" }
vide = { name = "alicesaidhi/vide", version = "^0.4.1-test.4" }
gt = { name = "corecii/greentea", version = "^0.4.11" }
ecr = { wally = "centau/ecr", version = "^0.9.0" }