name = "alicesaidhi/jabby_ecs_registry"
version = "0.1.0-test.1"
includes = ["src/*", "pesde.toml"]
license = "MIT"

[target]
environment = "roblox"
lib = "src/lib.luau"
build_files = ["src"]

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[indices]
default = "https://github.com/daimond113/pesde-index"

[dependencies]
jabby_types = { workspace = "alicesaidhi/jabby_types" }
jabby_core = { workspace = "alicesaidhi/jabby_core" }
jabby_ui = { workspace = "alicesaidhi/jabby_ui" }
jabby_net = { workspace = "alicesaidhi/jabby_net" }
jabby_query_parser = { workspace = "alicesaidhi/jabby_query_parser"}
vide = { wally = "centau/vide", version = "0.3.1" }
gt = { wally = "corecii/greentea", version = "^0.4.11" }
jabby_util = { workspace = "alicesaidhi/jabby_util" }