name = "alicesaidhi/jabby_net"
version = "0.1.0"
includes = ["src/*", "pesde.toml"]
license = "MIT"

[target]
environment = "roblox"
lib = "src/lib.luau"
build_files = ["src"]

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[indices]
default = "https://github.com/daimond113/pesde-index"

[dependencies]
jabby_core = { workspace = "alicesaidhi/jabby_core" }
jabby_types = { workspace = "alicesaidhi/jabby_types" }
jabby_util = { workspace = "alicesaidhi/jabby_util" }
gt = { name = "corecii/greentea", version = "^0.4.11" }
