name = "alicesaidhi/jabby_core"
version = "0.1.0-test.2"
includes = ["src/*", "pesde.toml"]
license = "MIT"

[target]
environment = "roblox"
lib = "src/lib.luau"
build_files = ["src"]

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[indices]
default = "https://github.com/daimond113/pesde-index"

[dependencies]
jabby_types = { workspace = "alicesaidhi/jabby_types" }
